### ISSUE TITLE
Lambda Function - AccessDenied 

### ISSUE THREAD

**Issue by agamm** [c6fc/warcannon#17] opened 2023-07-02 10:38 UTC
When running `warcannon deploy` I get:
> │ Error: error creating Lambda Function (1): AccessDeniedException: 
│       status code: 403, request id: ...
│ 
│   with aws_lambda_function.warcannon,
│   on lambda_warcannon_singlefire.tf.json line 51, in resource.aws_lambda_function.warcannon:
│   51:             }

And this is with a user that has full lambda permissions.
Is it a bug or am I doing something wrong?

**Comment by c6fc** [comment] 2023-08-02 14:42
Looks like Fusebit, the provider of the Lambda layer for Node 16.4.2 that WARCannon uses, has gone out of business, causing new deployments fail. There was a bug in Node 18 that forced us to pin that specific version. I'll check to see if the bug in Node 18 has been resolved, and get a push fixed one way or another.

**Comment by c6fc** [comment] 2023-08-02 15:24
I pushed a fix to dev, and confirmed that it was able to deploy & run campaigns on my side. Give the dev branch a shot and let me know if you have any issues.

One caveat at the moment is that dev is pinned to ARM/Graviton-based instances, so make sure you're using something like c7g in the nodeInstanceType of settings.json.

**Comment by agamm** [comment] 2023-08-02 16:16
It works! thanks! you rock. @c6fc

**Closed** 2023-09-01 08:53 UTC
